stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://www.pagedjs.org
  only:
    - master
  script:
    - npm i
    # your build command
    - hugo
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod