baseURL = "http://example.org/"
languageCode = "en-us"
title = "pagedjs, house of HTML printing" 
theme = "pagedjs"
# relativeURLs = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight= 1

  [[menu.main]]
    identifier = "blog"
    name = "Journal"
    url = "/posts/"
    weight= 1

  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    url = "/documentation/"
    weight= 2

  [[menu.main]]
    identifier = "cookbook"
    name = "Cook book"
    url = "/cookbook/"
    weight= 2

  [[menu.main]]
    identifier = "codeofconduct"
    name = "Code of Conduct"
    url = "/code-of-conduct.html"
    weight= 3

  [[menu.main]]
    identifier = "colophon"
    name = "Colophon"
    url = "/colophon/"
    weight= 4 
