backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "uploads/images/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Journal" # Used in the UI
    folder: "posts/" # The path to the folder where the documents are stored
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - {label: "draft", name: "draft", widget: "boolean"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "class", name: "class", widget: "string", default: "journal"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "cover", widget: "image"}
      - {label: "weight", name: "weight", widget: "string"}
      - {label: "intro", name: "intro", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
 