backend:
  name: gitlab
  repo: tools/pagedjs-website
  branch: master # Branch to update (optional; defaults to master)
  auth_type: implicit
  app_id: fca248c60f5baeb52964adf1e1e83c61d5b552d1672e9944cbeee6c8c948d4f5
  api_root: https://gitlab.pagedmedia.org/api/v4
  base_url: https://gitlab.pagedmedia.org
  auth_endpoint: oauth/authorize
publish_mode: editorial_workflow
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "uploads/images/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Journal" # Used in the UI
    folder: "content/posts/" # The path to the folder where the documents are stored
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - {label: "draft", name: "draft", widget: "boolean"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "intro", name: "intro", widget: "markdown"}
      - {label: "class", name: "class", widget: "string", default: "journal", required: false}
      - {label: "author", name: "author", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "cover", widget: "image", , required: false}
      - {label: "weight", name: "weight", widget: "string", , required: false}
      - {label: "Body", name: "body", widget: "markdown"}
 